config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {sessions: "admin/sessions"}
  devise_for :users, controllers: {sessions: "user/sessions"}
  resources :posts do
    resources :comments 
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	belongs_to :user
	validates_presence_of :title, :body
	validates_length_of :title, :in=> 5..30, :message=> "Titulo inválido"
	validates :body, length: {
		minimum: 10,
		maximum: 50,
		too_short: "El texto del post es demasiado corto (minimo %{count} palabras)",
		too_long: "El texto del post es demasiado largo (maximo %{count} palabras)"
	}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    if user_signed_in?
      @posts = current_user.posts
    else     
      @posts = Post.all
    end 
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        #flash[:success] = "El Post fue creado exitosamente"
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        flash[:alert] = "Ocurrio un problema al crear el Post :("
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>

  <section class="row">
    <div class="small-4 columns">
      <div class="actions">
        <%= f.submit 'Aceptar', :class => 'button small' %>
      </div>
    </div>
  </section>

<% end %>

app/views/posts/_navigation.html.erb
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">My App</li>
        <li><%= link_to 'Mostrar posts', posts_path %></li>   
        <% if user_signed_in? %>                  
            <li><%= link_to 'Crear nuevo post', new_post_path %></li>   
        <% end %>        
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
    	<% if user_signed_in? %>
      		<li>Logged in as <strong><%= current_user.email %></strong></li>
      		<li><%= link_to 'Editar perfil',edit_user_registration_path, :class=>'navbar-link'%></li>
      	 	<li><%= link_to 'Salir',destroy_user_session_path, method: :delete, :class=>'navbar-link'%></li>
      <% elsif admin_signed_in? %>
          <li>Logged in as admin <strong><%= current_admin.email %></strong></li>
          <li><%= link_to 'Editar perfil',edit_admin_registration_path, :class=>'navbar-link'%></li>
          <li><%= link_to 'Salir',destroy_admin_session_path, method: :delete, :class=>'navbar-link'%></li>
      <% else %>
      		<li><%= link_to 'Registro',new_user_registration_path, :class=>'navbar-link'%></li>
      		<li><%= link_to 'Ingresar',new_user_session_path, :class=>'navbar-link'%></li>
      <% end %>
    </ul>
  </div>  
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Post creados</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Contenido</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td>
          <% if post.body.length > 0 %>
            <a href="#" data-open="post-<%= post.id %>">Ver detalles</a>
            <div id="post-<%= post.id %>" class="reveal" data-reveal>
              <%= post.body %>
              <button class="close-button" data-close aria-label="cerrar" type="button">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          <% end %>
        </td>
        <td><%= link_to 'Mostrar', post %></td>
        <td><%= link_to 'Editar', edit_post_path(post) %></td>
        <% if admin_signed_in? %>
        <td><%= link_to 'Eliminar', post, method: :delete, data: { confirm: '¿Estas seguro de eliminarlo?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/posts/new.html.erb
<h1>Nuevo Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<div id="comments">
	<%= render :partial => @post.comments.reverse %>
</div>

<%= form_for([@post, Comment.new], remote: true) do |f| %>
	<p><%= f.label :body, "New Comment" %><br/>
		<%= f.text_area :body %>
	</p>
	<p><%= f.submit "Add Comment"%></p>
<% end %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>